### ISSUE TITLE
Customer facter fact error

### ISSUE THREAD

**Issue by grant-veepshosting** [104corp/puppet-corp104_codedeploy_agent#1]
Execution of file 'lib/facter/codedeploy_agent_version.rb' on agents where we use this module frequently returns "error while resolving custom fact "codedeploy_agent_version": undefined method `[]' for nil:NilClass".
Environment: Ubuntu 18.04 LTS on AWS + Puppet 6x latest.

I will open a PR if I manage to solve this.

**Comment by grant-veepshosting** [comment]
Here is a patch that fixes the above problem:
`--- corp104_codedeploy_agent_orig/lib/facter/codedeploy_agent_version.rb	2020-07-10 11:30:08.281669554 +1000
+++ corp104_codedeploy_agent/lib/facter/codedeploy_agent_version.rb	2020-07-10 11:31:03.698351735 +1000
@@ -5,7 +5,7 @@
   confine { Facter.value(:operatingsystem) != 'nexus' }
   setcode do
     if File.exists?('/opt/codedeploy-agent/.version')
-      Facter::Core::Execution.exec('cat /opt/codedeploy-agent/.version 2>&1').match(/^agent_version:\ OFFICIAL_(\d+\.\d+\-\d+\.\d+).*$/)[1]
+      Facter::Core::Execution.exec('cat /opt/codedeploy-agent/.version 2>&1').match(/^agent_version:\ OFFICIAL_(\d+\.\d+\.\d+\-\d+).*$/)[1]
     end
   end
 end`

The root cause is the version comes back with 3 digits prior to the hyphen '-' instead of 2 before and 2 after.

**Comment by yaosiang** [comment]
@grant-veepshosting  Thanks for your contribution 👍
